command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "8000"
  - --server.address
  - "0.0.0.0"
env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: ab79eced8207d29b
  - name: SECOPS_CATALOG
    value: lr_serverless_aws_us_catalog
  - name: SECOPS_LLM_ENDPOINT
    value: databricks-meta-llama-3-3-70b-instruct
  - name: SECOPS_VS_ENDPOINT
    value: ka-04bfe483-vs-endpoint
resources:
  - name: sql-warehouse
    sql_warehouse:
      id: ab79eced8207d29b
      permission: CAN_USE
